---
swagger: "2.0"
info:
  description: "Swagger spec for KeyworD project."
  version: "1.0.0"
  title: "Swagger KeyworD"
  contact:
    email: "iwanhae@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api"
schemes:
- "https"
- "http"
paths:
  /request:
    post:
      summary: "Requset a new query"
      description: "새로운 작업을 요청"
      operationId: "new_query"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Query"
      responses:
        "200":
          description: "정상 처리시 아이디 반환"
          schema:
            $ref: "#/definitions/inline_response_200"
        "400":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /progress/{id}:
    get:
      operationId: "show_progress"
      parameters:
      - name: "id"
        in: "path"
        description: "query to lookup"
        required: true
        type: "string"
      responses:
        "200":
          description: "정상 처리시 현재 상태 반환"
          schema:
            $ref: "#/definitions/Status"
        "404":
          description: "존재하지 않는 ID, total=-1"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /result/{id}:
    get:
      operationId: "show_result"
      parameters:
      - name: "id"
        in: "path"
        description: "query to lookup"
        required: true
        type: "string"
      responses:
        "200":
          description: "정상 처리시 작업결과 반환"
          schema:
            $ref: "#/definitions/Result"
        "400":
          description: "Invalid input"
        "404":
          description: "존재하지 않는 ID"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Data:
    type: "array"
    items:
      $ref: "#/definitions/Data_inner"
  Query:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/Data"
    example:
      data: ""
  Status:
    type: "object"
    properties:
      total:
        type: "integer"
      current:
        type: "integer"
      message:
        type: "string"
    example:
      total: 0
      current: 6
      message: "message"
  Result:
    type: "object"
    properties:
      from:
        type: "string"
        description: "시작날짜"
      to:
        type: "string"
        description: "종료날짜"
      data:
        $ref: "#/definitions/Data"
      related:
        type: "array"
        items:
          $ref: "#/definitions/Result_related"
    example:
      data: ""
      related:
      - data: ""
        similarity: 0.80082819046101150206595775671303272247314453125
        keyword: "keyword"
      - data: ""
        similarity: 0.80082819046101150206595775671303272247314453125
        keyword: "keyword"
      from: "from"
      to: "to"
  inline_response_200:
    type: "object"
    properties:
      id:
        type: "string"
    example:
      id: "id"
  Data_inner:
    type: "object"
    properties:
      date:
        type: "string"
      value:
        type: "number"
  Result_related:
    type: "object"
    properties:
      keyword:
        type: "string"
      similarity:
        type: "number"
        description: "그래프간 유사도. 크면 클수록 좋음"
      data:
        $ref: "#/definitions/Data"
    example:
      data: ""
      similarity: 0.80082819046101150206595775671303272247314453125
      keyword: "keyword"
